// <auto-generated />
using System;
using CoreEV4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreEV4.Migrations
{
    [DbContext(typeof(PatientsDbContext))]
    [Migration("20210816095328_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreEV4.Models.Hospitals", b =>
                {
                    b.Property<int>("hId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("hAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("hId");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("CoreEV4.Models.Patients", b =>
                {
                    b.Property<int>("pId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("bGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hId")
                        .HasColumnType("int");

                    b.Property<string>("pEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("pStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pId");

                    b.HasIndex("hId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CoreEV4.Models.Patients", b =>
                {
                    b.HasOne("CoreEV4.Models.Hospitals", "Hospitals")
                        .WithMany("Patients")
                        .HasForeignKey("hId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
